repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: detect-private-key
    - id: check-merge-conflict
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: no-commit-to-branch
      args: [--branch, main]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.3
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
