@startuml
actor User
actor TgUser
component NginxGateway
component TgBot

package Atopacake {
  component NginxAtopacake
  database PostgresAtopacake

  package FastApiApp {
    component Cards
    component Texts
    component Auth
  }
}


User -> NginxGateway
NginxGateway -> NginxAtopacake
NginxAtopacake -down-> FastApiApp
TgUser -> TgBot
TgBot -down-> NginxGateway
FastApiApp -down-> PostgresAtopacake
@enduml
