services:
  atopacake:
    image: atopacake
    container_name: atopacake_api
    restart: always
    env_file:
      - .env
    build: .

  postgres_atopacake_api:
    image: postgres:17.4
    container_name: postgres_atopacake_api
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/postgres_atopacake_api:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
